// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let smap = {}
    let tmap = {}
    for(let i=0;i<t.length;i++){
        if(smap[s[i]]){
            smap[s[i]]++
        }
        else{
            smap[s[i]]=1
        }
        if(tmap[t[i]]){
            tmap[t[i]]++
        }
        else{
            tmap[t[i]]=1
        }
    }
    for(const key in tmap){
        if(tmap[key]!==smap[key]){
            return key
        }
    }
};
